$(function(){
    $(".closeIco").show();
    $(".logo").click(function(){
        location.href='index.html';
    });
    $(".closeIco").click(function(){
        location.href='index.html';
    });
})